language: csharp
solution: ".NET Portable TypeCast.sln"
install:
  - nuget restore ".NET Portable TypeCast.sln"
  - nuget install nunit.consolerunner -Version 3.4.1 -OutputDirectory packages
script:
  - xbuild /p:Configuration=Release ".NET Portable TypeCast.sln"
  - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./TypeCast.Tests/bin/Release/Tests.dll
mono:
  - latest
  - 4.4.2
